# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c9ffa1a6f02a502a7f7c162a9bad901785bd551ee20093324f73bf64a7d931516a848890390793111b2176baaed5ed55a3b0f27051ad0d3c0acf938885a4c6f

test:
  secret_key_base: c902e09657aa49788f1f8b038f7565206aac9714bee5d5ab1a44d8ceb245fe3e0750e00baea6fd22ba99e1b60ec13d0fbc0491d6cea4f7a1c537069132304683

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
